research_company_culture_task:
  description: >
    Analyze the provided company website and the hiring manager's company's domain {company_domain},
    description {company_description}. Focus on understanding the company's culture, values, and mission.
    Identify unique selling points and specific projects or achievements highlighted on the site.
    
    Tool Usage Instructions:
    1. Use SerperDevTool to search for: "{company_domain} company culture", "{company_domain} mission values", 
       "{company_domain} employee reviews", and "{company_domain} recent news achievements"
    2. Use ScrapeWebsiteTool to extract content from key pages like /about, /careers, /values, /mission, 
       /team, and any blog or news sections on {company_domain}
    3. Cross-reference findings from multiple sources to build a comprehensive picture
    
    Compile a report summarizing these insights, specifically how they can be leveraged in a job posting
    to attract the right candidates.
  expected_output: >
    A comprehensive report detailing the company's culture, values, and mission, along with specific selling
    points relevant to the job role. Include sources used and suggestions on incorporating these insights 
    into the job posting.

research_role_requirements_task:
  description: >
    Based on the hiring manager's needs: {hiring_needs}, identify the key skills, experiences,
    and qualities the ideal candidate should possess for the role. Consider the company's current projects,
    its competitive landscape, and industry trends.
    
    Tool Usage Instructions:
    1. Use SerperDevTool to research: "current trends {hiring_needs} role 2024", "skills requirements 
       {hiring_needs} industry", and "salary benchmark {hiring_needs} {company_domain}"
    2. Use ScrapeWebsiteTool to examine the company's current projects, technology stack, and team 
       structure from their website, GitHub, or product pages
    3. Search for competitor job postings and industry standards for similar roles
    
    Prepare a list of recommended job requirements and qualifications that align with the company's 
    needs and values.
  expected_output: >
    A structured list of recommended skills, experiences, and qualities for the ideal candidate, 
    aligned with the company's culture, ongoing projects, and the specific role's requirements. 
    Include market research insights and competitive analysis.

draft_job_posting_task:
  description: >
    Draft a job posting for the role described by the hiring manager: {hiring_needs}.
    Use the insights on {company_description} to start with a compelling introduction,
    followed by a detailed role description, responsibilities, and required skills and qualifications.
    
    Tool Usage Instructions:
    1. Use FileReadTool to read and analyze the job_description_example.md file for structure, 
       formatting guidelines, and tone examples
    2. Use SerperDevTool to research current job market standards for similar roles, including 
       common benefits, perks, and industry-specific language
    3. Use ScrapeWebsiteTool to gather the latest company information, recent achievements, 
       or specific project details to make the posting more current and appealing
    4. Follow the structure and tone guidelines from the example file while customizing content
    
    Ensure the tone aligns with the company's culture and incorporate any unique benefits or
    opportunities offered by the company. Specific benefits: {specific_benefits}.
  expected_output: >
    A detailed, engaging job posting following the template structure that includes an introduction, 
    role description, responsibilities, requirements, and unique company benefits. The tone should 
    resonate with the company's culture and values, aimed at attracting the right candidates.

review_and_edit_job_posting_task:
  description: >
    Review the draft job posting for the role {hiring_needs}. Check for clarity, engagement, 
    grammatical accuracy, and alignment with the company's culture and values.
    
    Tool Usage Instructions:
    1. Use FileReadTool to compare the draft against job_description_example.md for consistency 
       in structure, formatting, and professional standards
    2. Use ScrapeWebsiteTool to verify all company information is accurate and up-to-date by 
       cross-checking with the official company website
    3. Use SerperDevTool to fact-check salary ranges, industry standards, and verify that 
       mentioned skills and requirements are current and realistic
    4. Ensure all claims about company culture and values align with official sources
    
    Edit and refine the content, ensuring it speaks directly to the desired candidates and 
    accurately reflects the role's unique benefits and opportunities.
  expected_output: >
    A polished, error-free job posting that is clear, engaging, and perfectly aligned with the 
    company's culture and values. Include specific feedback on improvements made, fact-checking 
    results, and final approval for publishing. Format the final output in markdown.

industry_analysis_task:
  description: >
    Conduct an in-depth analysis of the industry related to the company's domain {company_domain}.
    Investigate current trends, challenges, and opportunities within the industry.
    
    Tool Usage Instructions:
    1. Use SerperDevTool to research: "{company_domain} industry trends 2024", "challenges in 
       [industry] sector", "opportunities [industry] market", and "future outlook [industry]"
    2. Use ScrapeWebsiteTool to examine industry reports, market research pages, and competitor 
       websites to understand the competitive landscape
    3. Search for recent expert opinions, market analysis, and industry publications
    4. Cross-reference multiple sources to validate trends and insights
    
    Assess how these factors could impact the role being hired for and the overall attractiveness 
    of the position to potential candidates. Consider how the company's position within this industry 
    and its response to these trends could be leveraged to attract top talent.
  expected_output: >
    A detailed analysis report that identifies major industry trends, challenges, and opportunities 
    relevant to the company's domain and the specific job role. Include specific sources and data 
    points. Provide strategic insights on positioning the job role and the company as an attractive 
    choice for potential candidates, with actionable recommendations for the job posting.