research_company_culture_task:
  description: >
    Analyze the company website {company_domain} and description {company_description} to understand 
    the company's culture, values, mission, and unique selling points.
    
    TOOL USAGE INSTRUCTIONS:
    1. Use SerperDevTool to search for:
       - "{company_domain} company culture values mission statement"
       - "{company_domain} employee reviews glassdoor indeed"
       - "{company_domain} recent news achievements press releases 2024"
       - "{company_domain} work environment benefits perks"
       - "{company_domain} diversity inclusion initiatives"
    
    2. Use ScrapeWebsiteTool to extract content from:
       - https://{company_domain}/about (or /about-us)
       - https://{company_domain}/careers (or /jobs)
       - https://{company_domain}/values (or /culture)
       - https://{company_domain}/mission
       - https://{company_domain}/team (or /leadership)
       - Any blog or news sections on the main website
    
    3. Cross-reference findings from multiple sources to build comprehensive picture
    4. Focus on details that align with hiring needs: {hiring_needs}

  expected_output: >
    A comprehensive company culture report including:
    1. Company mission, vision, and core values
    2. Unique culture highlights and work environment
    3. Recent achievements or notable projects
    4. Employee benefits and perks
    5. Key selling points for attracting candidates
    6. Sources used for research
    
    Format as a structured report with clear sections.

research_role_requirements_task:
  description: >
    Based on the hiring manager's needs "{hiring_needs}" and company information, research and define 
    the ideal candidate profile. Consider current market trends and industry standards.
    
    TOOL USAGE INSTRUCTIONS:
    1. Use SerperDevTool to search for:
       - "current market trends {hiring_needs} role 2024"
       - "skills requirements {hiring_needs} industry standards"
       - "salary benchmark {hiring_needs} {company_domain} location"
       - "{hiring_needs} job description examples top companies"
       - "in-demand skills {hiring_needs} 2024"
       - "career progression {hiring_needs} role"
    
    2. Use ScrapeWebsiteTool to examine:
       - Company's current projects and technology stack from their website
       - Product pages to understand technical requirements
       - Engineering/tech blog posts for technology insights
       - Current job openings on company careers page for similar roles
       - GitHub repositories if publicly available
    
    3. Research competitor companies and their job requirements for similar roles
    4. Use company culture insights from previous task to align requirements

  expected_output: >
    A detailed candidate profile including:
    1. Essential technical skills (3-5 key skills)
    2. Required experience level and background
    3. Important soft skills and qualities
    4. Nice-to-have qualifications
    5. Salary range based on market research
    6. Cultural fit indicators
    
    Present as structured lists with brief explanations.

draft_job_posting_task:
  description: >
    Create a compelling job posting for the role: {hiring_needs}
    
    TOOL USAGE INSTRUCTIONS:
    1. Use FileReadTool to:
       - Read job_description_example.md file completely
       - Analyze structure, formatting, and tone guidelines
       - Note section headers and content organization
       - Reference professional language patterns
    
    2. Use SerperDevTool to search for:
       - "best job posting examples {hiring_needs} role 2024"
       - "job posting templates {hiring_needs} industry"
       - "engaging job description language recruitment"
       - "job posting best practices attract candidates"
       - "current benefits trends tech companies 2024"
    
    3. Use ScrapeWebsiteTool to:
       - Get latest company information and recent achievements from {company_domain}
       - Check careers page for current job posting format and style
       - Gather specific project details mentioned on website
       - Verify company benefits and perks listed on official pages
    
    4. Use research insights from previous tasks to craft content that:
       - Opens with exciting company introduction
       - Clearly describes role impact and responsibilities
       - Highlights unique benefits: {specific_benefits}
       - Reflects company culture and values

  expected_output: >
    A complete job posting in markdown format with these sections:
    1. Job Title
    2. Company Overview (2-3 paragraphs)
    3. Role Summary (1-2 paragraphs)
    4. Key Responsibilities (bullet points)
    5. Required Qualifications (bullet points)
    6. Preferred Qualifications (bullet points)
    7. Benefits & Perks
    8. How to Apply
    
    Use professional yet engaging tone throughout.

review_and_edit_job_posting_task:
  description: >
    Review and polish the draft job posting to ensure it meets professional standards.
    
    TOOL USAGE INSTRUCTIONS:
    1. Use FileReadTool to:
       - Compare draft against job_description_example.md template
       - Check for structural consistency and formatting standards
       - Verify adherence to professional tone and style guidelines
       - Ensure all required sections are present and well-formatted
    
    2. Use ScrapeWebsiteTool to:
       - Verify all company information is accurate by cross-checking with {company_domain}
       - Confirm company values, mission, and culture claims are current
       - Check that mentioned benefits and perks match official company pages
       - Validate any specific project or technology details mentioned
    
    3. Use SerperDevTool to:
       - Fact-check salary ranges and market standards for {hiring_needs} role
       - Verify technical skills and requirements are current and realistic
       - Research industry standards for similar positions in 2024
       - Check if mentioned technologies, tools, or methodologies are still relevant
       - Validate job market trends and requirements mentioned
    
    4. Review checklist:
       - Grammar, spelling, and clarity
       - Professional yet engaging tone
       - Accuracy of all company and role information
       - Market-appropriate requirements and compensation
       - Complete and well-structured format
       - Alignment with company culture from research

  expected_output: >
    A polished, final job posting in clean markdown format ready for publication. 
    Include a brief summary of improvements made during the review process.
    
    The final output should be a complete, professional job description that accurately 
    represents the company and role while attracting qualified candidates.